name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write  # GitHub Pages için gerekli izinler

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: GitHub Pages'i Yapılandır
        uses: actions/configure-pages@v3
        with:
          enablement: true  # Pages yapılandırmasını etkinleştir

      - name: Siteyi İnşa Et
        run: |
          bundle install
          bundle exec jekyll build

      - name: GitHub Pages'ı Yayına Al
        uses: actions/deploy-pages@v2
