name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write  # Pages erişimi için kritik yetki

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: GitHub Pages’i Yapılandır
        uses: actions/configure-pages@v3
        with:
          enablement: true  # GitHub Pages’i etkinleştir

      - name: Siteyi İnşa Et
        run: |
          mkdir _site
          echo "Merhaba Dünya" > _site/index.html

      - name: GitHub Pages’i Yayına Al
        uses: actions/deploy-pages@v2
