name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3

      - name: GitHub Pages'ı Yapılandır
        uses: actions/configure-pages@v3
        with:
          enablement: true

      - name: Jekyll Kur ve Siteyi İnşa Et
        run: |
          bundle install
          bundle exec jekyll build

      - name: Sayfayı Yayınla
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

      - name: GitHub Pages'ı Yayına Al
        id: deployment
        uses: actions/deploy-pages@v2
