name: Weekly Competitor PageSpeed Audit

on:
  schedule:
    - cron: '0 0 * * 1'  # Her Pazartesi 00:00'da çalışır
  workflow_dispatch:  # Manuel olarak çalıştırmak için

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3
        
      - name: Python Kurulumu
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Bağımlılıkları Kur
        run: pip install requests
        
      - name: PageSpeed Testi Çalıştır (Rakipler)
        run: python scripts/pagespeed.py
        
      - name: Sonuçları Yükle
        uses: actions/upload-artifact@v3
        with:
          name: Competitor PageSpeed Raporu
          path: reports/
